### ISSUE TITLE
Domoticz won't connect to Omnik converter after last Beta update Domoticz

### ISSUE THREAD

**Issue by ghost** [sincze/Domoticz-Omnik-Local-Web-Plugin#11]
Ik update Domoticz to the last beta (Version: 2022.1 (build 14352)) and now Domoticz won't receive any data from Omnik converter.
Converter is still running since Solarman is still getting the data and I can acces the converter ont its own IP address 192.168.2.7.

2022-06-03 10:47:29.342 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.343 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.343 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.345 Error: SOLAR_PANELS: Call to function 'onMessage' failed, exception details:
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: Traceback (most recent call last):
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: File "/home/pi/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 221, in onMessage
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: _plugin.onMessage(Connection, Data)
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: File "/home/pi/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 133, in onMessage
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: strData = Data["Data"].decode("utf-8", "ignore")
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: KeyError: 'Data'
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.378 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.379 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.379 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.380 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.380 Error: SOLAR_PANELS: Exception processing 'ReadEvent' message.
2022-06-03 10:47:29.381 Error: SOLAR_PANELS: Exception processing 'DisconnectedEvent' message

any idea?

**Comment by waltervl** [comment]
I have the same issue. It is now also in stable 2022.2

debug log
`2022-11-07 21:20:24.533  PP Omnik: Debug logging mask set to: PYTHON PLUGIN IMAGE DEVICE CONNECTION 
2022-11-07 21:20:24.533  PP Omnik: 'HardwareID':'6'
2022-11-07 21:20:24.533  PP Omnik: 'HomeFolder':'/home/bolt/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/'
2022-11-07 21:20:24.533  PP Omnik: 'StartupFolder':'/home/bolt/domoticz/'
2022-11-07 21:20:24.533  PP Omnik: 'UserDataFolder':'/home/bolt/domoticz/'
2022-11-07 21:20:24.533  PP Omnik: 'Database':'/home/bolt/domoticz/domoticz.db'
2022-11-07 21:20:24.533  PP Omnik: 'Language':'en'
2022-11-07 21:20:24.533  PP Omnik: 'Version':'1.0.1'
2022-11-07 21:20:24.533  PP Omnik: 'Author':'sincze'
2022-11-07 21:20:24.533  PP Omnik: 'Name':'PP Omnik'
2022-11-07 21:20:24.533  PP Omnik: 'Address':'192.168.1.42'
2022-11-07 21:20:24.533  PP Omnik: 'Port':'0'
2022-11-07 21:20:24.533  PP Omnik: 'Username':'xxxxx'
2022-11-07 21:20:24.533  PP Omnik: 'Password':'xxxxxx'
2022-11-07 21:20:24.533  PP Omnik: 'Key':'OmnikLocalWeb'
2022-11-07 21:20:24.533  PP Omnik: 'Mode1':'80'
2022-11-07 21:20:24.533  PP Omnik: 'Mode2':'2'
2022-11-07 21:20:24.533  PP Omnik: 'Mode6':'62'
2022-11-07 21:20:24.533  PP Omnik: 'DomoticzVersion':'2022.2 (build 14599)'
2022-11-07 21:20:24.533  PP Omnik: 'DomoticzHash':'1b733567d'
2022-11-07 21:20:24.533  PP Omnik: 'DomoticzBuildTime':'2022-11-04 18:00:18'
2022-11-07 21:20:24.533  PP Omnik: Device count: 3
2022-11-07 21:20:24.533  PP Omnik: Device:           1 - ID: 85, Name: 'Omnik - Inverter (kWh)', nValue: 0, sValue: '0.0;4788900.0'
2022-11-07 21:20:24.534  PP Omnik: Device ID:       '85'
2022-11-07 21:20:24.534  PP Omnik: Device Name:     'Omnik - Inverter (kWh)'
2022-11-07 21:20:24.534  PP Omnik: Device nValue:    0
2022-11-07 21:20:24.534  PP Omnik: Device sValue:   '0.0;4788900.0'
2022-11-07 21:20:24.534  PP Omnik: Device LastLevel: 0
2022-11-07 21:20:24.534  PP Omnik: Device:           2 - ID: 86, Name: 'Omnik - Inverter (W)', nValue: 0, sValue: '0.0'
2022-11-07 21:20:24.534  PP Omnik: Device ID:       '86'
2022-11-07 21:20:24.534  PP Omnik: Device Name:     'Omnik - Inverter (W)'
2022-11-07 21:20:24.534  PP Omnik: Device nValue:    0
2022-11-07 21:20:24.534  PP Omnik: Device sValue:   '0.0'
2022-11-07 21:20:24.534  PP Omnik: Device LastLevel: 0
2022-11-07 21:20:24.534  PP Omnik: Device:           3 - ID: 87, Name: 'Omnik - Inverter Status', nValue: 1, sValue: 'On'
2022-11-07 21:20:24.534  PP Omnik: Device ID:       '87'
2022-11-07 21:20:24.534  PP Omnik: Device Name:     'Omnik - Inverter Status'
2022-11-07 21:20:24.534  PP Omnik: Device nValue:    1
2022-11-07 21:20:24.534  PP Omnik: Device sValue:   'On'
2022-11-07 21:20:24.534  PP Omnik: Device LastLevel: 0
2022-11-07 21:20:24.534  (PP Omnik) Creating images from file '/home/bolt/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/Omnik.zip'.
2022-11-07 21:20:24.536  PP Omnik: Image created. ID: 102
2022-11-07 21:20:24.536  PP Omnik: Plugin is started.
2022-11-07 21:20:24.536  PP Omnik: Protocol set to: 'HTTP'.
2022-11-07 21:20:24.536  PP Omnik: Transport set to: 'TCP/IP', 192.168.1.42:80.
2022-11-07 21:20:24.537  PP Omnik: Connect directive received, action initiated successfully.
2022-11-07 21:20:24.549  Status: OpenAQ Python: Initialized version 3.0, author 'Xorfor'
2022-11-07 21:20:24.551  OpenAQ Python: Debug logging mask set to: NONE
2022-11-07 21:20:24.869  Status: PluginSystem: 2 plugins started.
2022-11-07 21:20:24.887  PP Omnik: Inverter connected successfully.
2022-11-07 21:20:24.887  PP Omnik: Sending 237 bytes of data
2022-11-07 21:20:24.962  PP Omnik: Received 226 bytes of data
2022-11-07 21:20:24.962  PP Omnik: Received 179 bytes of data
2022-11-07 21:20:24.962  Error: PP Omnik: Exception processing 'ReadEvent' message.
2022-11-07 21:20:24.962  PP Omnik: Received 12 bytes of data
2022-11-07 21:20:24.962  Error: PP Omnik: Exception processing 'ReadEvent' message.
2022-11-07 21:20:24.962  PP Omnik: Received 16 bytes of data
2022-11-07 21:20:24.962  Error: PP Omnik: Exception processing 'ReadEvent' message.
2022-11-07 21:20:24.962  Queued asynchronous read aborted (192.168.1.42:80), [2] End of file.
2022-11-07 21:20:24.962  PP Omnik: HTTP Details (2):
2022-11-07 21:20:24.962  PP Omnik: --->'Status':'200'
2022-11-07 21:20:24.962  PP Omnik: --->'Headers (7):
2022-11-07 21:20:24.962  PP Omnik: ------->'Server':'Ralink HTTPD'
2022-11-07 21:20:24.962  PP Omnik: ------->'Date':'Thu, 01 Jan 1970 07:24:05 GMT'
2022-11-07 21:20:24.962  PP Omnik: ------->'Pragma':'no-cache'
2022-11-07 21:20:24.962  PP Omnik: ------->'Cache-Control':'no-cache'
2022-11-07 21:20:24.962  PP Omnik: ------->'Content-Type':'application/x-javascript'
2022-11-07 21:20:24.962  PP Omnik: ------->'Last-Modified':'Tue, 27 Feb 2018 17:20:11 GMT'
2022-11-07 21:20:24.962  PP Omnik: ------->'Connection':'close'
2022-11-07 21:20:24.962  Error: PP Omnik: Call to function 'onMessage' failed, exception details:
2022-11-07 21:20:24.967  Error: PP Omnik: Traceback (most recent call last):
2022-11-07 21:20:24.967  Error: PP Omnik:   File "/home/bolt/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 221, in onMessage
2022-11-07 21:20:24.967  Error: PP Omnik:     _plugin.onMessage(Connection, Data)
2022-11-07 21:20:24.967  Error: PP Omnik:   File "/home/bolt/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 133, in onMessage
2022-11-07 21:20:24.967  Error: PP Omnik:     strData = Data["Data"].decode("utf-8", "ignore")
2022-11-07 21:20:24.967  Error: PP Omnik: KeyError: 'Data'
2022-11-07 21:20:24.967  PP Omnik: Local context:
2022-11-07 21:20:24.967  PP Omnik:  ----> 'Devices'              '{1: <Domoticz.Device object at 0x7f7bcc462c10>, 2: <Domoticz.Device object at 0x7f7bcc462cb0>, 3: <Domoticz.Device object at 0x7f7bcc462d50>}'
2022-11-07 21:20:24.967  PP Omnik:  ----> 'Domoticz'             '<module 'Domoticz' (built-in)>'
2022-11-07 21:20:24.967  PP Omnik:  ----> 'Images'               '{'Omnik': <Domoticz.Image object at 0x7f7bcc3d88f0>}'
2022-11-07 21:20:24.967  PP Omnik:  ----> 'Parameters'           '{'HardwareID': 6, 'HomeFolder': '/home/bolt/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/', 'StartupFolder': '/home/bolt/domoticz/', 'UserDataFolder': '/home/bolt/domoticz/', 'WebRoot': '', 'Database': '/home/bolt/domoticz/domoticz.db', 'Language': 'en', 'Version': '1.0.1', 'Author': 'sincze', 'Name': 'PP Omnik', 'Address': '192.168.1.42', 'Port': '0', 'SerialPort': '', 'Username': 'xxxxxx', 'Password': 'xxxxxxx', 'Key': 'OmnikLocalWeb', 'Mode1': '80', 'Mode2': '2', 'Mode3': '', 'Mode4': '', 'Mode5': '', 'Mode6': '62', 'DomoticzVersion': '2022.2 (build 14599)', 'DomoticzHash': '1b733567d', 'DomoticzBuildTime': '2022-11-04 18:00:18'}'

2022-11-07 21:20:24.968  PP Omnik:  ----> '_plugin'              '<plugin.BasePlugin object at 0x7f7bcc4cdd30>'
2022-11-07 21:20:24.968  PP Omnik:  ----> 'local'                'False'
2022-11-07 21:20:24.968  PP Omnik:  ----> 're'                   '<module 're' from '/usr/lib/python3.8/re.py'>'
2022-11-07 21:20:24.968  PP Omnik: Received 4096 bytes of data
2022-11-07 21:20:24.968  Error: PP Omnik: Exception processing 'ReadEvent' message.
2022-11-07 21:20:24.968  PP Omnik: Received 3310 bytes of data
2022-11-07 21:20:24.968  Error: PP Omnik: Exception processing 'ReadEvent' message.
2022-11-07 21:20:24.968  Error: PP Omnik: Exception processing 'DisconnectedEvent' message.
2022-11-07 21:20:34.096  PP Omnik: onHeartbeat called, Connection is alive.
2022-11-07 21:20:44.074  PP Omnik: onHeartbeat called, Connection is alive.`

**Comment by waltervl** [comment]
To add: the link http://inverter-ip/js/status.js is working fine and gives data but somehow it is read differently in the new Python framework.

**Comment by sincze** [comment]
> To add: the link http://inverter-ip/js/status.js is working fine and gives data but somehow it is read differently in the new Python framework.

Tnx, I need to update to 2022.2 to verify why it is broken then.

**Comment by rik1984** [comment]
I have exactly the same issue right after my update to 2022.2. Any ideas on solutions yet? I've also tried to update my Python, without a solution

**Comment by sincze** [comment]
The problem at the moment is that I leave my home in the Dark and come back in the Dark, That means the inverter is offline when I return, so hard to debug. 

The problem originates with Domoticz itself as before updating Domoticz the plugin works just fine. That is why I moved a lot of my work to Pass2PHP scripts (see my github). Pass2PHP only depends on Domoticz API's and not the framework.

**Comment by waltervl** [comment]
I made a temporary dzvents script that renders the status.js and puts the data in a new dummy electricoty meter. Waiting for the updated plugin to get a better result.

**Comment by sincze** [comment]
Interesting indeed, just started a Domoticz docker (as you can see) and can reproduce the issue on this version of Domoticz.
```
2022-11-18 09:33:24.153 Error: Omnik: Call to function 'onMessage' failed, exception details:
2022-11-18 09:33:24.154 Error: Omnik: Traceback (most recent call last):
2022-11-18 09:33:24.154 Error: Omnik: File "/opt/domoticz/userdata/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 221, in onMessage
2022-11-18 09:33:24.154 Error: Omnik: _plugin.onMessage(Connection, Data)
2022-11-18 09:33:24.154 Error: Omnik: File "/opt/domoticz/userdata/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 133, in onMessage
2022-11-18 09:33:24.154 Error: Omnik: strData = Data["Data"].decode("utf-8", "ignore")
2022-11-18 09:33:24.154 Error: Omnik: KeyError: 'Data'
```

**Comment by sincze** [comment]
![image](https://user-images.githubusercontent.com/5776333/203121327-3aa82a0b-05a6-4160-a4d5-28befd2c4a77.png)
Got this today after coming home. Looks okay

**Comment by sincze** [comment]
Bumped Plugin to v1.0.2

**Comment by ghost** [comment]
I still get the same problem.

2022-11-22 17:26:38.732 Status: PluginSystem: Started, Python version '3.4.4', 2 plugin definitions loaded.
2022-11-22 17:26:38.791 Status: WebServer(HTTP) started on address: :: with port 80
2022-11-22 17:26:38.852 Status: WebServer(SSL) started on address: :: with port 443
2022-11-22 17:26:38.870 Status: TCPServer: shared server started...
2022-11-22 17:26:38.871 Status: RxQueue: queue worker started...
2022-11-22 17:26:40.880 Omnik: Worker thread started.
2022-11-22 17:26:40.872 Status: EnergieMeter: Using serial port: /dev/ttyUSB0
2022-11-22 17:26:40.880 Status: Omnik: Started.
2022-11-22 17:26:40.886 Status: EnergieMeter: Worker started...
2022-11-22 17:26:40.887 Status: Omnik: Entering work loop.
2022-11-22 17:26:40.925 Status: RaspberryPI: System: Raspberry Pi
2022-11-22 17:26:41.002 Status: EventSystem: reset all events...
2022-11-22 17:26:41.006 Status: EventSystem: reset all device statuses...
2022-11-22 17:26:41.017 Status: NotificationSystem: thread started...
2022-11-22 17:26:41.018 Status: RaspberryPI: Hardware Monitor: Started (OStype Raspberry Pi Linux)
2022-11-22 17:26:41.088 Status: PluginSystem: 1 plugins started.
2022-11-22 17:26:43.417 Omnik: Image created. ID: 101
2022-11-22 17:26:43.418 Omnik: Plugin is started.
2022-11-22 17:26:43.271 Status: Omnik: Initialized version 1.0.2, author 'sincze'
2022-11-22 17:26:43.467 Status: Python EventSystem: Initializing event module.
2022-11-22 17:26:43.472 Status: EventSystem: Started
2022-11-22 17:26:43.473 Status: EventSystem: Queue thread started...
2022-11-22 17:26:43.523 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:43.524 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:43.525 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:43.526 Error: Omnik: Call to function 'onMessage' failed, exception details:
2022-11-22 17:26:44.031 Error: Omnik: Traceback (most recent call last):
2022-11-22 17:26:44.031 Error: Omnik: File "/home/pi/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 221, in onMessage
2022-11-22 17:26:44.031 Error: Omnik: _plugin.onMessage(Connection, Data)
2022-11-22 17:26:44.032 Error: Omnik: File "/home/pi/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 137, in onMessage
2022-11-22 17:26:44.032 Error: Omnik: strData = Data["Data"].decode("utf-8", "ignore")
2022-11-22 17:26:44.032 Error: Omnik: KeyError: 'Data'
2022-11-22 17:26:44.032 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:44.033 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:44.034 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:44.035 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:44.036 Error: Omnik: Exception processing 'ReadEvent' message.
2022-11-22 17:26:44.042 Error: Omnik: Exception processing 'DisconnectedEvent' message.
2022-11-22 17:26:48.609 Status: EnergieMeter: Meter reports as DSMR 4.2
2022-11-22 17:30:43.436 Status: EventSystem: reset all events...

**Comment by waltervl** [comment]
I also still have the issue after update. 
Python Version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]

> 2022-11-22 18:37:04.761 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.762 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.762 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.762 Error: Omnik: Call to function 'onMessage' failed, exception details:
> 2022-11-22 18:37:04.772 Error: Omnik: Traceback (most recent call last):
> 2022-11-22 18:37:04.772 Error: Omnik: File "/home/udoox86/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 221, in onMessage
> 2022-11-22 18:37:04.772 Error: Omnik: _plugin.onMessage(Connection, Data)
> 2022-11-22 18:37:04.772 Error: Omnik: File "/home/udoox86/domoticz/plugins/Domoticz-Omnik-Local-Web-Plugin/plugin.py", line 137, in onMessage
> 2022-11-22 18:37:04.772 Error: Omnik: strData = Data["Data"].decode("utf-8", "ignore")
> 2022-11-22 18:37:04.772 Error: Omnik: KeyError: 'Data'
> 2022-11-22 18:37:04.823 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.823 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.824 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.825 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.825 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.826 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.827 Error: Omnik: Exception processing 'ReadEvent' message.
> 2022-11-22 18:37:04.828 Error: Omnik: Exception processing 'DisconnectedEvent' message.
>

**Comment by sincze** [comment]
![image](https://user-images.githubusercontent.com/5776333/204490964-ae0439be-c8bb-4460-8c53-b317f3ac0e09.png)
I did a DOCKER setup side by side... Clearly there is something in Domoticz that changed.

**Comment by sincze** [comment]
![image](https://github.com/sincze/Domoticz-Omnik-Local-Web-Plugin/assets/5776333/da7a7579-f2b6-4c9b-ad31-0f8584881a78)
Currently working on v2.0.0 so it can be used in Domoticz again. First signs look promissing

**Comment by sincze** [comment]
Please follow this thread for the running prototype
https://github.com/sincze/Domoticz-Omnik-Local-Web-Plugin/issues/12

**Comment by sincze** [comment]
Testing of new version is now possible

`git pull https://github.com/sincze/Domoticz-Omnik-Local-Web-Plugin dev
`

**Comment by sincze** [comment]
We will continue the discussion here https://github.com/sincze/Domoticz-Omnik-Local-Web-Plugin/issues/12
